# Generated by Django 3.0 on 2019-12-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sid',
            new_name='uid',
        ),
    ]
