# Generated by Django 3.0 on 2019-12-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191208_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='sample@mail.com', max_length=100),
            preserve_default=False,
        ),
    ]
