# Generated by Django 3.0 on 2019-12-12 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('disc', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='task1', to='tasks.Task')),
                ('task10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task10', to='tasks.Task')),
                ('task2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task2', to='tasks.Task')),
                ('task3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task3', to='tasks.Task')),
                ('task4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task4', to='tasks.Task')),
                ('task5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task5', to='tasks.Task')),
                ('task6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task6', to='tasks.Task')),
                ('task7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task7', to='tasks.Task')),
                ('task8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task8', to='tasks.Task')),
                ('task9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task9', to='tasks.Task')),
            ],
            options={
                'db_table': 'recipes',
                'ordering': ('id',),
            },
        ),
    ]
