# Generated by Django 3.0 on 2019-12-12 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_usertask'),
        ('recipes', '0002_userrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecipe',
            name='task1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='task1', to='tasks.UserTask'),
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='task10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task10', to='tasks.UserTask'),
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='task2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task2', to='tasks.UserTask'),
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='task3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task3', to='tasks.UserTask'),
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='task4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task4', to='tasks.UserTask'),
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='task5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task5', to='tasks.UserTask'),
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='task6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task6', to='tasks.UserTask'),
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='task7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task7', to='tasks.UserTask'),
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='task8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task8', to='tasks.UserTask'),
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='task9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task9', to='tasks.UserTask'),
        ),
    ]
